### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by panicpan2000** [TaoShuchang/CANA#1]
Hi, Thanks for your work. I ran the code but met a problem.
FileNotFoundError: [Errno 2] No such file or directory: '../checkpoint/surrogate_model_gcn/ogbproducts_partition_checkpoint.pt'
In this case, I should train a surrogate model first and I try to run gnn_model/gcn.py to get the file. However, I met Unresolved reference 'EarlyStopping' in gnn_model/gcn.py. 
Could you fix the process of obtaining the checkpoint?

Another problem is which scripts and parameters can reproduce the result without CANA or with HAO.
Thank you.

**Comment by TaoShuchang** [comment]
Hi, @panicpan2000 
I apologize for the delay in response. I've updated the repository and addressed the issues you've pointed out. 

1. The GNN checkpoints, including the file '../checkpoint/surrogate_model_gcn/ogbproducts_partition_checkpoint.pt', have been uploaded to the checkpoint directory. This should resolve the FileNotFoundError you were encountering.

2. I've also fixed the reference issue with 'EarlyStopping' in the gnn_model/gcn.py. This should now allow you to train the surrogate model without any issues.

3. As for the code and scripts without CANA or with HAO, I will upload the corresponding codes in a few days. 

I appreciate your patience and your help in identifying these problems.
In the meantime, please try running the code again with the updated files. If you encounter any more issues or have any questions, don't hesitate to reach out.

Thanks again for your valuable feedback.

**Comment by panicpan2000** [comment]
Thanks!
